### Create a new task
POST http://localhost:3000/api/tasks
Content-Type: application/json

{
  "title": "Task with Due Date",
  "description": "This is task with a due date.",
  "dueDate": "2025-06-30T00:00:00.000Z"
}

### Get all tasks
GET http://localhost:3000/api/tasks
Content-Type: application/json


### Get a specific task by ID
GET http://localhost:3000/api/tasks/684feb19a7c713cc15c9ed03
Content-Type: application/json

### Update a specific task by ID
PUT http://localhost:3000/api/tasks/684feb38a7c713cc15c9ed07
Content-Type: application/json

{
  "dueDate": "2025-10-01T00:00:00.000Z"
}

### Delete a specific task by ID
DELETE http://localhost:3000/api/tasks/684fd7808c72721ecbd10ebb
Content-Type: application/json