### Create a new task
POST http://localhost:3000/api/tasks
Content-Type: application/json

{
    "title": "Update Documentation",
    "description": "Go through the API documentation and make necessary updates based on the recent changes. Add missing endpoint examples and update version references.",
    "completed": false,
    "dueDate": "2025-11-10T00:00:00.000Z"
}

### Get all tasks
GET http://localhost:3000/api/tasks
Content-Type: application/json


### Get a specific task by ID
GET http://localhost:3000/api/tasks/684feb19a7c713cc15c9ed03
Content-Type: application/json

### Update a specific task by ID
PUT http://localhost:3000/api/tasks/685010e2f1b438c194626cbb
Content-Type: application/json

{
  "dueDate": "2025-03-15T00:00:00.000Z"
}

### Delete a specific task by ID
DELETE http://localhost:3000/api/tasks/684fd7808c72721ecbd10ebb
Content-Type: application/json

### Register a new user
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "username": "newuser@mail.com",
  "password": "newpassword123"
}

### User login
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "username": "newuser@mail.com",
  "password": "newpassword123"
}